#!/bin/bash

awk '{print $1,$3}' FS=: /etc/passwd | sort -n -k 2

#awk {print $1,$3} - get 1st and 3rd words in a delemiter (default - space)
#FS=: - change delimeter to :
#sort -n - sort numbers
#-k 2 - sort by 2nd column
