#!/bin/bash

rm output2
touch output2
chmod 777 output2

for dir in $(ls /proc/ | grep "[0-9]\+") 
do
if test -f "/proc/$dir/cmdline"; then
if grep -qa "/sbin" /proc/$dir/cmdline 
then echo $dir >> output2
fi
fi
done

#test -f - test if file exists
#if grep - check if match found
#then append proc (dir) name to file
